export const T_TKN = 't_tkn'
export const USER_FOLLOWS_IDS = 'user_follows_ids'
export const TWITCH_TV = 'https://twitch.tv/'
export const TWITCH_USERS_URL = 'https://api.twitch.tv/helix/users'
export const TWITCH_VALIDATE_URL = 'https://id.twitch.tv/oauth2/validate'
export const TWITCH_CLIENT_ID = '8jq2ki0ir3dpbur253h2l3y078finx'
// export const TWITCH_CLIENT_ID = 'uxqwi7vcviwp1o7448pji91a3tokjp'
// export const TWITCH_CLIENT_ID = 'k5pq19rmj1wyj6fozwb1e6hznerk5k'
// PROD
// export const TWITCH_CLIENT_ID = 'a0zmx4iwj3v27gw4editvecq1bvjx5'
export const REVOKE_TWITCH_URL = 'https://id.twitch.tv/oauth2/revoke'
export const TWITCH_USERS_FOLLOWS = `https://api.twitch.tv/helix/users/follows`
export const TWITCH_GET_STREAMS = 'https://api.twitch.tv/helix/streams'
export const TWITCH_QUERY_CHANNELS = 'https://api.twitch.tv/helix/search/channels'
export const TWITCH_GAMES = 'https://api.twitch.tv/helix/games'
export const TWITCH_SUBSCRIPTIONS = 'https://api.twitch.tv/helix/eventsub/subscriptions'
